# Generated by Django 3.1.8 on 2022-11-19 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.IntegerField()),
                ('last_transaction', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'configuracoes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='demo_images')),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meses',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.IntegerField(choices=[(1, 'Gestor'), (2, 'Professor'), (3, 'Aluno Adulto'), (4, 'Aluno Infantil')])),
                ('nome', models.CharField(max_length=30)),
                ('nome_responsavel', models.CharField(blank=True, max_length=30)),
                ('data_vencimento', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')], null=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pessoas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sedes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dias', models.IntegerField(choices=[(1, 'Segunda Quarta'), (2, 'Terca Quinta')])),
                ('horario', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('pessoa_professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.pessoa')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sede')),
            ],
            options={
                'db_table': 'turmas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TurmaAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('pessoa_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pessoa')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.turma')),
            ],
            options={
                'db_table': 'turma_alunos',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TurmaAlunoPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('link', models.CharField(default='', max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Pagamento Gerado'), (2, 'Pagameto Pendente'), (3, 'Pagamento Efetuado')], default=1)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('mes_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mes')),
                ('turma_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.turmaaluno')),
            ],
            options={
                'db_table': 'aluno_pagamentos',
                'ordering': ['created_at'],
            },
        ),
    ]
