# Generated by Django 3.1.8 on 2022-11-18 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.IntegerField(choices=[(1, 'Gestor'), (2, 'Professor'), (3, 'Aluno')])),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=20)),
                ('data_vencimento', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pessoas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlunoPagameto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.IntegerField()),
                ('valor', models.FloatField()),
                ('link', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Nao Iniciado'), (2, 'Pagamento Gerado'), (3, 'Pagameto Pendente'), (4, 'Pagamento Efetuado')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('pessoa_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pessoa')),
            ],
            options={
                'db_table': 'aluno_pagamentos',
                'ordering': ['created_at'],
            },
        ),
    ]
