# Generated by Django 3.1.8 on 2022-11-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alunopagameto_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cpf',
        ),
    ]
