# Generated by Django 3.1.8 on 2022-11-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20221121_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='expoPushToken',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
