# Generated by Django 3.1.8 on 2022-11-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20221119_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunopagameto',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pagamento Gerado'), (2, 'Pagameto Pendente'), (3, 'Pagamento Efetuado')], default=1),
        ),
    ]
