# Generated by Django 3.1.8 on 2022-11-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pessoa_expopushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='tipo_dias',
            field=models.IntegerField(choices=[(1, 'Segunda e Quarta'), (2, 'Terça e Quinta')]),
        ),
    ]
