# Generated by Django 3.1.8 on 2022-11-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20221124_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='status',
        ),
        migrations.AddField(
            model_name='turmaaluno',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')], default=1),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_vencimento',
            field=models.IntegerField(null=True),
        ),
    ]
