# Generated by Django 3.1.8 on 2022-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_configuracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunopagameto',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
