# Generated by Django 4.1.3 on 2022-11-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctis_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunopagametos',
            old_name='pessoa_aluno_id',
            new_name='pessoa_aluno',
        ),
        migrations.RenameField(
            model_name='pessoas',
            old_name='user_id',
            new_name='user',
        ),
    ]
