# Generated by Django 4.1.3 on 2022-11-17 00:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctis_api', '0002_rename_pessoa_aluno_id_alunopagametos_pessoa_aluno_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlunoPagametos',
            new_name='AlunoPagameto',
        ),
        migrations.RenameModel(
            old_name='Pessoas',
            new_name='Pessoa',
        ),
    ]
