# Generated by Django 4.1.3 on 2022-11-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctis_api', '0004_alter_alunopagameto_table_alter_pessoa_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default='08282201405', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_vencimeto',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='Eduardo', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(default='1023', max_length=20),
            preserve_default=False,
        ),
    ]
