# Generated by Django 4.1.3 on 2022-11-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctis_api', '0005_pessoa_cpf_pessoa_data_vencimeto_pessoa_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='data_vencimeto',
            new_name='data_vencimento',
        ),
    ]
