# Generated by Django 4.1.3 on 2022-11-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctis_api', '0006_rename_data_vencimeto_pessoa_data_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunopagameto',
            name='mes_referencia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alunopagameto',
            name='status',
            field=models.IntegerField(choices=[(1, 'Nao Iniciado'), (2, 'Pagamento Gerado'), (3, 'Pagameto Pendente'), (4, 'Pagamento Efetuado')], default=1),
        ),
        migrations.AddField(
            model_name='alunopagameto',
            name='valor',
            field=models.FloatField(default=115),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo_pessoa',
            field=models.IntegerField(choices=[(1, 'Gestor'), (2, 'Professor'), (3, 'Aluno')], default=1),
            preserve_default=False,
        ),
    ]
