# Generated by Django 4.1.3 on 2022-11-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctis_api', '0007_alunopagameto_mes_referencia_alunopagameto_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunopagameto',
            name='link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
